import { Header } from "@/components/Headers/index";
import { Footer } from "@/components/Footer";
import { WhatsApp } from "@/components/WhatsApp";
import { Montserrat, Bebas_Neue } from "next/font/google";
import SmoothScroll from "@/hooks/SmoothScroll";
import "./globals.scss";

const montse = Montserrat({
  variable: "--font-normal",  
  subsets: ['latin'], // choose at least one
  weight: '400',
  preload: true,
})
const bebas = Bebas_Neue({
  variable: "--font-bold",    
  subsets: ['latin'], // or ['latin', 'latin-ext'] if you need more characters  
  weight: '400',
  preload: true,
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={`${montse.variable} ${bebas.variable}`}>

        <SmoothScroll/>
        <Header />
        {children}
        <WhatsApp/>
        <Footer/>

      </body>
    </html>
  );
}
